config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { registrations: 'registrations' }
  as :user do
    get 'gurus/logout' => 'devise/sessions#destroy', :as => :delete_user_session
  end

  root 'pages#home'

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      get :gist
    end
  end

  resources :contacts, only: %i[new create]

  resources :badges, only: %i[index]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index

    resources :badges, except: :show
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  enum rule: {
    all_by_category: 0,
    on_first_try: 1,
    all_by_level: 2
  }

  has_many :badges_users, dependent: :destroy
  has_many :users, through: :badges_users

  validates :title, :image, :rule, :subject_name, presence: true
  validate :comparison_subject_name_and_test_name, if: :on_first_try?
  validate :comparison_subject_name_and_category_name, if: :all_by_category?
  validate :comparison_subject_name_and_level, if: :all_by_level?

  def comparison_subject_name_and_test_name
    errors.add(:subject_name, "doesn't exist") unless Test.where(title: subject_name).present?
  end

  def comparison_subject_name_and_category_name
    errors.add(:subject_name, "doesn't exist") unless Category.where(title: subject_name).present?
  end

  def comparison_subject_name_and_level
    errors.add(:subject_name, "doesn't exist") unless Test.where(level: subject_name).present?
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < ApplicationController
  before_action :set_badges, only: %i[index]
  before_action :set_badge, only: %i[destroy edit update]

  def index

  end

  def show

  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path, notice: t('.success')
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path, notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path, notice: t('.success')
  end

  private

  def set_badges
    @badges = Badge.all
  end

  def badge_params
    params.require(:badge).permit(:title, :image, :rule, :subject_name)
  end

  def set_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badges, only: %i[index]

  def index

  end

  private

  def set_badges
    @badges = Badge.all
    @user_badges = current_user.badges
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
<td class="align-"><%= badge.title %></td>
  <td class="align-middle"><img src="<%= badge.image %>" height="50"></td>
  <td class="align-middle"><%= link_to t('.links.edit'), edit_admin_badge_path(badge) %></td>
<td class="align-middle">
<%= link_to t('.links.delete'), admin_badge_path(badge),
                method: :delete,
                data: { confirm: t('.delete_notice') } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>

  <div class="form-group">

    <div class="mb-3">
      <%= form.label :title, class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :rule, class: 'form-label' %>
      <%= form.select :rule,
                      options_for_select(Badge.rules.map { |k, v| [k.titleize, Badge.rules.key(v)] }, @badge.rule),
                      { prompt: true },
                      class: 'form-select' %>
    </div>

    <div class="mb-3">
      <%= form.label :subject_name %>
      <%= form.text_field :subject_name, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :image, class: 'form-label' %>
      <%= form.text_field :image, class: 'form-control' %>
    </div>

    <%= form.submit class: 'btn btn-primary' %>

  </div>
<% end %>

app/views/admin/badges/edit.html.erb
<div class="row justify-content-center mt-3 mx-3">
  <div class="col col-md-6">

    <h1><%= t('.header') %></h1>

    <%= render 'form' %>

    <p class="mt-3"><%= link_to t('.links.back'), admin_badges_path %></p>

  </div>
</div>

app/views/admin/badges/index.html.erb
<div class="row justify-content-center mt-3 mx-3">
  <div class="col col-md-12">

    <h1><%= t('.header') %></h1>

    <p><%= link_to t('.links.new_badge'), new_admin_badge_path, class: 'btn btn-primary' %></p>

    <table class="table md-6">
      <thead>
      <tr>
        <th><%= t('.title') %></th>
        <th><%= t('.image') %></th>
        <th colspan="3"><%= t('.action') %></th>
      </tr>
      </thead>
      <tbody>

      <%= render @badges %>

    </table>
  </div>
</div>

app/views/admin/badges/new.html.erb
<div class="row justify-content-center mt-3 mx-3">
  <div class="col col-md-6">

    <h1><%= t('.header') %></h1>

    <%= render 'form' %>

    <p class="mt-3"><%= link_to t('.links.back'), admin_badges_path %></p>

  </div>
</div>