config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { registrations: 'registrations' }
  as :user do
    get 'gurus/logout' => 'devise/sessions#destroy', :as => :delete_user_session
  end

  root 'pages#home'

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      get :gist
    end
  end

  resources :contacts, only: %i[new create]

  resources :badges, only: %i[index]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index

    resources :badges, except: :show
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :set_next_question
  before_update :update_completed

  MIN_SUCCESS_PERCENTAGE = 85

  def completed?
    current_question.nil?
  end

  def success_percentage
    ((correct_questions.to_f / test.questions.count) * 100).round
  end

  def current_progress
    passed_questions_count = test.questions.order(:id).index(current_question)
    (passed_questions_count.to_f / test.questions.count * 100).round
  end

  def successfull?
    success_percentage >= MIN_SUCCESS_PERCENTAGE && !time_over?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def question_number
    self.test.questions.order(:id).index(current_question) + 1
  end

  def time_over?
    return false if test.timer.nil?

    created_at + test.timer.minutes < Time.zone.now
  end

  private

  def update_completed
    self.completed = true if successfull?
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count

    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
      correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end

  def set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :set_test_passage, only: %i[show update result gist]

  def show
    @remaining_seconds = @test_passage.created_at + @test_passage.test.timer.minutes - Time.zone.now
  end

  def result

  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed? || @test_passage.time_over?
      TestsMailer.completed_test(@test_passage).deliver_now
      BadgeService.new(@test_passage).call

      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    client = Octokit::Client.new(access_token: ENV.fetch('GITHUB_TOKEN', nil))
    service = GistQuestionService.new(@test_passage.current_question, client)
    result = service.call
    gist_url = result.html_url

    flash_options = service.success? ? { notice: t('.success', link: result.html_url) } : { danger: t('.failed') }

    save_gist(gist_url)

    redirect_to @test_passage, flash_options
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def save_gist(gist_url)
    @test_passage.current_question.gists.create(
      user_id: @test_passage.user.id,
      url: gist_url
    )
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def timer(times_up)
    tag.div(id: 'timer',
            class: 'row justify-content-center border rounded-pill mb-4',
            data: { times_up: })
  end
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<p>
  <%= t('.correct') %> <%= @test_passage.correct_questions %> <%= t('.from') %> <%= @test_passage.test.questions.count %>.<br>
  <%= t('.percentage') %>:
  <span class="<%= @test_passage.successfull? ? 'success-test-passage' : 'failed-test-passage' %>">
    <%= @test_passage.success_percentage %>%
  </span>
</p>

<p><%= @test_passage.successfull? ? t('.success') : t('.failure') %></p>

<%= link_to t('.links.tests'), tests_path %>

app/views/test_passages/show.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>
<h2><%= t('.question') %> <%= @test_passage.question_number %> <%= t('.from') %> <%= @test_passage.test.questions.count %></h2>

<%= timer(@remaining_seconds.to_i) %>

<div class="progress mb-4">
  <div
      class="progress-bar bg-success" role="progressbar"
      style="width: <%= @test_passage.current_progress %>%"
      aria-valuenow="<%= @test_passage.current_progress %>"
      aria-valuemin="0" aria-valuemax="100">
  </div>
</div>

<p>
<b><%= @test_passage.current_question.body %></b>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to t('.links.create_gist'), gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit t('.buttons.next'), id: 'next-question' %></p>
<% end %>