config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { registrations: 'registrations' }
  as :user do
    get 'gurus/logout' => 'devise/sessions#destroy', :as => :delete_user_session
  end

  root 'pages#home'

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      get :gist
    end
  end

  resources :contacts, only: %i[new create]

  resources :badges, only: %i[index]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index

    resources :badges, except: :show
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  ANSWERS_LIMIT = 4

  validates :body, presence: true
  validate :validate_number_of_answers

  scope :correct, -> { where(correct: true) }

  private

  def validate_number_of_answers
    errors.add(:answers) if question.answers.count > ANSWERS_LIMIT
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.build(answer_params)

    if @answer.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: :show

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<li>
  <%= answer.body %><br>
  <%= link_to 'Посмотреть', answer_path(answer) %>
</li>

app/views/answers/_form.html.erb
<%= form_with model: [@question, @answer], local: true do |form| %>
  <p>
    <%= form.label :body %>
    <%= form.text_area :body, id: :answer_body, rows: 6, cols: 50 %>
  </p>

  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p><%= form.submit button_text %></p>
<% end %>

app/views/answers/edit.html.erb
<h1>Изменение варианта ответа</h1>

<p><%= @answer.question.body %></p>

<%= render 'form', button_text: 'Изменить'%>
<%= link_to 'Назад', question_path(@answer.question) %>

app/views/answers/new.html.erb
<h1>Создание нового варианта ответа</h1>

<p><%= @question.body %></p>

<%= render 'form', button_text: 'Создать' %>
<%= link_to 'Назад', question_path(@question) %>

app/views/answers/show.html.erb
<h1>Вопрос</h1>

<p> <%= @answer.question.body %></p>

<p>
  <b>Вариант ответа:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Верный ответ:</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Назад', question_path(@answer.question) %>