config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { registrations: 'registrations' }
  as :user do
    get 'gurus/logout' => 'devise/sessions#destroy', :as => :delete_user_session
  end

  root 'pages#home'

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      get :gist
    end
  end

  resources :contacts, only: %i[new create]

  resources :badges, only: %i[index]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index

    resources :badges, except: :show
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  ANSWERS_LIMIT = 4

  validates :body, presence: true
  validate :validate_number_of_answers

  scope :correct, -> { where(correct: true) }

  private

  def validate_number_of_answers
    errors.add(:answers) if question.answers.count > ANSWERS_LIMIT
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  enum rule: {
    all_by_category: 0,
    on_first_try: 1,
    all_by_level: 2
  }

  has_many :badges_users, dependent: :destroy
  has_many :users, through: :badges_users

  validates :title, :image, :rule, :subject_name, presence: true
  validate :comparison_subject_name_and_test_name, if: :on_first_try?
  validate :comparison_subject_name_and_category_name, if: :all_by_category?
  validate :comparison_subject_name_and_level, if: :all_by_level?

  def comparison_subject_name_and_test_name
    errors.add(:subject_name, "doesn't exist") unless Test.where(title: subject_name).present?
  end

  def comparison_subject_name_and_category_name
    errors.add(:subject_name, "doesn't exist") unless Category.where(title: subject_name).present?
  end

  def comparison_subject_name_and_level
    errors.add(:subject_name, "doesn't exist") unless Test.where(level: subject_name).present?
  end
end

app/models/badges_user.rb
class BadgesUser < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :tests

  validates :title, presence: true

  default_scope { order(title: :asc) }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: :User, foreign_key: :author_id
  has_many :test_passages, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than: 0 }
  validates :timer, numericality: { only_integer: true,  greater_than_or_equal_to: 0 }

  scope :published, -> { where(published: true ) }
  scope :easy, -> { where(level: 0..1).order(created_at: :desc) }
  scope :medium, -> { where(level: 2..4).order(created_at: :desc) }
  scope :hard, -> { where(level: 5..Float::INFINITY).order(created_at: :desc) }
  scope :category_name, -> (name) { joins(:category).where(category: { title: name }) }

  def self.tests_by_category(name)
    category_name(name).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :set_next_question
  before_update :update_completed

  MIN_SUCCESS_PERCENTAGE = 85

  def completed?
    current_question.nil?
  end

  def success_percentage
    ((correct_questions.to_f / test.questions.count) * 100).round
  end

  def current_progress
    passed_questions_count = test.questions.order(:id).index(current_question)
    (passed_questions_count.to_f / test.questions.count * 100).round
  end

  def successfull?
    success_percentage >= MIN_SUCCESS_PERCENTAGE && !time_over?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def question_number
    self.test.questions.order(:id).index(current_question) + 1
  end

  def time_over?
    return false if test.timer.nil?

    created_at + test.timer.minutes < Time.zone.now
  end

  private

  def update_completed
    self.completed = true if successfull?
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count

    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
      correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end

  def set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :author_tests, class_name: :Test, inverse_of: :author, foreign_key: :author_id
  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :gists, dependent: nil
  has_many :badges_user, dependent: :destroy
  has_many :badges, through: :badges_user

  validates :first_name, :last_name, presence: true

  def tests_by_level(level)
    tests.where(level:)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_year
    Time.zone.now.year
  end

  def github_url(author, repo)
    link_to 'TestGuru', "https://github.com/#{author}/#{repo}", target: '_blank', rel: 'noopener'
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/gist_helper.rb
module GistHelper
  def gist_question_link(gist)
    question = gist.question
    truncated = question.body.truncate(25)

    link_to truncated, admin_question_path(question), class: 'text-decoration-none'
  end

  def gist_link(gist)
    hash = URI.parse(gist.url).path.split('/').last

    link_to hash, gist.url, target: '_blank', class: 'text-decoration-none', rel: 'noopener'
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def flash_message
    flash.map do |key, message|
      content_tag( :div, sanitize(message, attributes: %w[href target]), class: "alert alert-#{key}")
    end.join
  end
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/_footer.html.erb
<hr/>
<div class="d-flex justify-content-left">
  <hr/>
  <%= link_to t('.links.contacts'), new_contact_path, class: 'text-blue-300 text-decoration-none' %>
</div>
<p>
  <%= current_year %> <%= author %>,
  <%= github_url(author, repo) %>
</p>
<p>
  <%= link_to t('.think'), 'https://thinknetica.com/', target: '_blank' %>
</p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin Panel | TestGuru</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'shared/header' %>
<%= render 'shared/flash' %>
<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testguru</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
<%= render 'shared/header' %>
<div class="container">
<%= render 'shared/flash' %>
<%= yield %>
</div>
<%= render 'layouts/footer', author: 'mativagon', repo: 'testguru' %>
</body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message, class: "flash #{key}" if message.present? %>
<% end %>

app/views/shared/_header.html.erb
<span class="navbar navbar-light bg-primary">
  <div class="container">
<h1><%= link_to 'TestGuru', root_path, class: 'navbar-brand px-3 text-white' %></br></h1>
    <% if user_signed_in? %>
    <div class="nav col-12 px-3 text-white">
  <%= t('.welcome') %>, <%= current_user.first_name %>!</br>
    </div>
      <% if current_user&.admin? %>
         <div class="nav col-12 text-white">
    <%= link_to t('.links.admin'), admin_tests_path, class: 'nav-link text-white' %>
         </div>
        <div class="nav col-12 text-white">
    <%= link_to t('.badge'), admin_badges_path, class: "nav-link text-white" %>
         </div>
    <% end %>
      <div class="nav col-12 text-white">
      <%= link_to t('.links.logout'), delete_user_session_path, method: :delete, class: 'nav-link text-white' %>
        </div>
      <div class="nav col-12 text-white">
      <%= link_to t('.links.badge'), badges_path, class: "nav-link text-white" %>
        </div>
<% else %>
      <div class="nav col-12 text-white">
  <%= link_to t('.links.sign_up'), new_user_registration_path, class: 'nav-link text-white' %>
      <%= link_to t('.links.sign_in'), user_session_path, class: 'nav-link text-white' %>
      </div>
<% end %>
</div>
</span>